### ISSUE TITLE
Blogpost::validate() issues validating FeatuedImage

### ISSUE THREAD

**Issue by grgcnnr** [silverstripe/silverstripe-blog#409]
Validate appears to be called several times when a BlogPost is saved. But the Behaviour of the featured images is inconsistent across the calls.

Lets say we do something like this on BlogPost or a child class:

```
    protected function validate(){
      Debug::show($this->FeaturedImage()->exists());
      return parent::validate();
    }
```

Then add an image an hit 'save;

```
Debug (BlogPost->validate() in BlogPost.php:702)
(bool) false

Debug (BlogPost->validate() in BlogPost.php:702)
(bool) true

Debug (BlogPost->validate() in BlogPost.php:702)
(bool) true

Debug (BlogPost->validate() in BlogPost.php:702)
(bool) true
```

Likewise removing an image and hitting save 
```
Debug (BlogPost->validate() in BlogPost.php:702)
(bool) true

Debug (BlogPost->validate() in BlogPost.php:702)
(bool) false

Debug (BlogPost->validate() in BlogPost.php:702)
(bool) false

Debug (BlogPost->validate() in BlogPost.php:702)
(bool) false
```

This is problematic if you wish to enforce a FeaturedImage object because anything like:

```
if(!$this->FeaturedImage()->exists()){
  // Throw a validation error
}
```

Will always fail on the first round.

Is this expected behaviour and I'm just missing something here?

<3 G

**Comment by micmania1** [comment]
I'm not sure why validate is being called so many times, but I suspect this is the case for all SilverStripe page types and the problem probably lies in the cms or framework. Likewise with saving/validating an image or any has_one in this way.

If you do something like this does it work consistently?

```
$featuredImage = Image::get()->byId($this->FeaturedImageID);
if($featuredImage) { // exists }
```

**Comment by grgcnnr** [comment]
Thanks @micmania1 

Nope, ID isn't set until too late.
```
 public function validate() {
   Debug::show($this->FeaturedImageID);
   return parent::validate();
}
```

```
Debug (BlogPost->validate() in BlogPost.php:23)
0

Debug (BlogPost->validate() in BlogPost.php:23)
586

```

Is this an issue you can replicate? I can cause it in my project and with a clean version of SS (3.4) with only blog (2.4) installed.

If no one else can see it though maybe it's a quirk of my setup and also my stage server setup too.... :|

**Comment by micmania1** [comment]
It would be interesting to know where the first validate was being called. Can you try throwing an error and posting the backtrace for it?

**Comment by grgcnnr** [comment]
Well. That doesn't seem right?

```
             try {
                $result = $this->validate();
             }catch(Exception $e) {
              debug::log( (debug_backtrace());
             }
```
```
== Thu, 30 Jun 2016 10:41:20 +1200 ==
#0 /Users/grg/www/blogtest/blog/code/model/BlogPost.php(36): BlogPost->validate()
#1 /Users/grg/www/blogtest/framework/model/DataObject.php(1210): BlogPost->validateWrite()
#2 /Users/grg/www/blogtest/framework/model/DataObject.php(1370): DataObject->preWrite()
#3 /Users/grg/www/blogtest/framework/model/Versioned.php(742): DataObject->write()
#4 [internal function]: Versioned->writeWithoutVersion()
#5 /Users/grg/www/blogtest/framework/core/Object.php(711): call_user_func_array(Array, Array)
#6 /Users/grg/www/blogtest/cms/code/controllers/CMSMain.php(897): Object->__call('writeWithoutVer...', Array)
#7 /Users/grg/www/blogtest/cms/code/controllers/CMSMain.php(897): BlogPost->writeWithoutVersion()
#8 /Users/grg/www/blogtest/framework/forms/Form.php(462): CMSMain->save(Array, Object(CMSForm), Object(SS_HTTPRequest))
#9 /Users/grg/www/blogtest/framework/control/RequestHandler.php(288): Form->httpSubmission(Object(SS_HTTPRequest))
#10 /Users/grg/www/blogtest/framework/control/RequestHandler.php(200): RequestHandler->handleAction(Object(SS_HTTPRequest), 'httpSubmission')
#11 /Users/grg/www/blogtest/framework/control/RequestHandler.php(222): RequestHandler->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#12 /Users/grg/www/blogtest/framework/control/Controller.php(158): RequestHandler->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#13 /Users/grg/www/blogtest/framework/admin/code/LeftAndMain.php(454): Controller->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#14 /Users/grg/www/blogtest/framework/admin/code/AdminRootController.php(92): LeftAndMain->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#15 /Users/grg/www/blogtest/framework/control/Director.php(385): AdminRootController->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#16 /Users/grg/www/blogtest/framework/control/Director.php(149): Director::handleRequest(Object(SS_HTTPRequest), Object(Session), Object(DataModel))
#17 /Users/grg/www/blogtest/framework/main.php(188): Director::direct('/admin/pages/ed...', Object(DataModel))
#18 {main}
```

**Comment by grgcnnr** [comment]
Validation Pass 2

```
== Thu, 30 Jun 2016 10:51:48 +1200 ==
#0 /Users/grg/www/blogtest/blog/code/model/BlogPost.php(42): BlogPost->validate()
#1 /Users/grg/www/blogtest/framework/model/DataObject.php(1210): BlogPost->validateWrite()
#2 /Users/grg/www/blogtest/framework/model/DataObject.php(1370): DataObject->preWrite()
#3 /Users/grg/www/blogtest/cms/code/controllers/CMSMain.php(912): DataObject->write()
#4 /Users/grg/www/blogtest/cms/code/controllers/CMSMain.php(1132): CMSMain->save(Array, Object(CMSForm))
#5 /Users/grg/www/blogtest/framework/forms/Form.php(462): CMSMain->publish(Array, Object(CMSForm), Object(SS_HTTPRequest))
#6 /Users/grg/www/blogtest/framework/control/RequestHandler.php(288): Form->httpSubmission(Object(SS_HTTPRequest))
#7 /Users/grg/www/blogtest/framework/control/RequestHandler.php(200): RequestHandler->handleAction(Object(SS_HTTPRequest), 'httpSubmission')
#8 /Users/grg/www/blogtest/framework/control/RequestHandler.php(222): RequestHandler->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#9 /Users/grg/www/blogtest/framework/control/Controller.php(158): RequestHandler->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#10 /Users/grg/www/blogtest/framework/admin/code/LeftAndMain.php(454): Controller->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#11 /Users/grg/www/blogtest/framework/admin/code/AdminRootController.php(92): LeftAndMain->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#12 /Users/grg/www/blogtest/framework/control/Director.php(385): AdminRootController->handleRequest(Object(SS_HTTPRequest), Object(DataModel))
#13 /Users/grg/www/blogtest/framework/control/Director.php(149): Director::handleRequest(Object(SS_HTTPRequest), Object(Session), Object(DataModel))
#14 /Users/grg/www/blogtest/framework/main.php(188): Director::direct('/admin/pages/ed...', Object(DataModel))
#15 {main}

```

**Comment by micmania1** [comment]
Can you confirm whether this happens on all page types or is this issue limited to BlogPost?

**Comment by grgcnnr** [comment]
Good point! It appears to be across all pages so I guess whatever it is, it's not really a blog issue.

**Comment by pxwee5** [comment]
So what should I do in order to validate the BlogPost's FeaturedImage using DataExtension?
